-- Create the UVM schema
CREATE USER UVM IDENTIFIED BY "UVM_password";

-- Grant necessary privileges to UVM
GRANT CONNECT, RESOURCE TO UVM;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO UVM;
ALTER USER UVM QUOTA UNLIMITED ON USERS;

-- Create the BANINST1 schema
CREATE USER BANINST1 IDENTIFIED BY "BANINST1_password";

-- Grant necessary privileges to BANINST1
GRANT CONNECT, RESOURCE TO BANINST1;
GRANT CREATE SESSION TO BANINST1;
ALTER USER BANINST1 QUOTA UNLIMITED ON USERS;

-- Create the SATURN schema
CREATE USER SATURN IDENTIFIED BY "SATURN_password";

-- Grant necessary privileges to SATURN
GRANT CONNECT, RESOURCE TO SATURN;
GRANT CREATE SESSION TO SATURN;
ALTER USER SATURN QUOTA UNLIMITED ON USERS;

-- Create the TAISMGR schema
CREATE USER TAISMGR IDENTIFIED BY "TAISMGR_password";

-- Grant necessary privileges to TAISMGR
GRANT CONNECT, RESOURCE TO TAISMGR;
GRANT CREATE SESSION TO TAISMGR;
ALTER USER TAISMGR QUOTA UNLIMITED ON USERS;

-- Create the BANSECR schema
CREATE USER BANSECR IDENTIFIED BY "BANSECR_password";

-- Grant necessary privileges to BANSECR
GRANT CONNECT, RESOURCE TO BANSECR;
GRANT CREATE SESSION TO BANSECR;
ALTER USER BANSECR QUOTA UNLIMITED ON USERS;

-- Create the TIBCO01 schema
CREATE USER TIBCO01 IDENTIFIED BY "TIBCO01_password";

-- Grant necessary privileges to TIBCO01
GRANT CONNECT, RESOURCE TO TIBCO01;
GRANT CREATE SESSION TO TIBCO01;
ALTER USER TIBCO01 QUOTA UNLIMITED ON USERS;

-- Create the TIBCO02 schema
CREATE USER TIBCO02 IDENTIFIED BY "TIBCO02_password";

-- Grant necessary privileges to TIBCO02
GRANT CONNECT, RESOURCE TO TIBCO02;
GRANT CREATE SESSION TO TIBCO02;
ALTER USER TIBCO02 QUOTA UNLIMITED ON USERS;

-- Create the TIBCO03 schema
CREATE USER TIBCO03 IDENTIFIED BY "TIBCO03_password";

-- Grant necessary privileges to TIBCO03
GRANT CONNECT, RESOURCE TO TIBCO03;
GRANT CREATE SESSION TO TIBCO03;
ALTER USER TIBCO03 QUOTA UNLIMITED ON USERS;

-- Create the TIBCO04 schema
CREATE USER TIBCO04 IDENTIFIED BY "TIBCO04_password";

-- Grant necessary privileges to TIBCO04
GRANT CONNECT, RESOURCE TO TIBCO04;
GRANT CREATE SESSION TO TIBCO04;
ALTER USER TIBCO04 QUOTA UNLIMITED ON USERS;

-- Commit the changes
COMMIT;

-- Print a success message
PROMPT All schemas created successfully.